Projeto01/Areas/Cadastros/Controllers/ProdutosController.cs
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using Modelo.Cadastros;
using System.Net;
using Servicos.Cadastros;
using Servicos.Tabelas;
using System.Web;
using System.IO;
using System;

namespace Projeto01.Areas.Cadastros.Controllers
{
    public class ProdutosController : Controller
    {
        private ProdutoServico produtoServico = new ProdutoServico();
        private CategoriaServico categoriaServico = new CategoriaServico();
        private FabricanteServico fabricanteServico = new FabricanteServico();

        private void PopularViewBag(Produto produto = null)
        {
            if (produto == null)
            {
                ViewBag.CategoriaId = new SelectList(categoriaServico.ObterCategoriasClassificadasPorNome(), "CategoriaId", "Nome");
                ViewBag.FabricanteId = new SelectList(fabricanteServico.ObterFabricantesClassificadosPorNome(), "FabricanteId", "Nome");
            }
            else
            {
                ViewBag.CategoriaId = new SelectList(categoriaServico.ObterCategoriasClassificadasPorNome(), "CategoriaId", "Nome", produto.CategoriaId);
                ViewBag.FabricanteId = new SelectList(fabricanteServico.ObterFabricantesClassificadosPorNome(), "FabricanteId", "Nome", produto.FabricanteId);
            }
        }

        private ActionResult ObterVisaoProdutoPorId(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = produtoServico.ObterProdutoPorId((long)id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Produtos
        public ActionResult Index()
        {
            return View(produtoServico.ObterProdutosClassificadosPorNome());
        }

       
        // GET: Produtos/Details/5
        public ActionResult Details(long? id)
        {
            return ObterVisaoProdutoPorId(id);
        }

        // GET: Produtos/Delete/5
        public ActionResult Delete(long? id)
        {
            return ObterVisaoProdutoPorId(id);
        }
              

        // GET: Produtos/Edit/5
        public ActionResult Edit(long? id)
        {
            PopularViewBag(produtoServico.ObterProdutoPorId((long)id));
            return ObterVisaoProdutoPorId(id);
        }

        // GET: Produtos/Create
        public ActionResult Create()
        {
            PopularViewBag();
            return View();
        }

        private ActionResult GravarProduto(Produto produto, HttpPostedFileBase logotipo, string chkRemoverImagem)
        {
            try
            {
                if (ModelState.IsValid)
                {   
                    if(chkRemoverImagem != null)
                    {
                        produto.Logotipo = null;
                    }
                    if(logotipo != null)
                    {
                        produto.LogotipoMineType = logotipo.ContentType;
                        produto.Logotipo = SetLogotipo(logotipo);


                    }
                    produtoServico.GravarProduto(produto);
                    return RedirectToAction("Index");
                }
                PopularViewBag(produto);
                return View(produto);
            }
            catch
            {
                PopularViewBag(produto);
                return View(produto);
            }
        }

        private byte[] SetLogotipo(HttpPostedFileBase logotipo)
        {
            var bytesLogotipo = new byte[logotipo.ContentLength];
            logotipo.InputStream.Read(bytesLogotipo, 0, logotipo.ContentLength);
            return bytesLogotipo;
        }

        public FileContentResult GetLogotipo(long id)
        {
            Produto produto = produtoServico.ObterProdutoPorId(id);
            if(produto != null)
            {
                return File(produto.Logotipo, produto.LogotipoMineType);
            }
            return null;
        }



        // POST: Produtos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Produto produto, HttpPostedFileBase logotipo = null, string chkRemoverImagem = null)
        {
            return GravarProduto(produto, logotipo, chkRemoverImagem);
        }

        // POST: Produtos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Produto produto, HttpPostedFileBase logotipo = null, string chkRemoverImagem = null)
        {
            return GravarProduto(produto, logotipo, chkRemoverImagem);
        }

        // POST: Produtos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long id)
        {
            try
            {
                Produto produto = produtoServico.EliminarProdutoPorId(id);
                TempData["Message"] = "Produto " + produto.Nome.ToUpper() + " foi removido";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Projeto01/Areas/Cadastros/Views/Produtos/Create.cshtml
@model Modelo.Cadastros.Produto

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Novo Produto";
}
@using (Html.BeginForm("Create", "Produtos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

                <div class="panel panel-primary">
        <div class="panel-heading">
            Cadastro de PRODUTOS
        </div>
        <div class="panel-body">
           
           @Html.Partial("~/Areas/Cadastros/Views/Produtos/_PartialEditContentPanel.cshtml")
        </div>
        <div class="panel-footer panel-info">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar Produto" class="btn btn-danger" />
                @Html.ActionLink("Retornar para a listagem de PRODUTOS", "Index", null, new { @class = "btn btn-warning" })
            </div>
            <br />
            <br />
        </div>
    </div>
    @section styles{
        <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet">
        <link href="@Url.Content("~/scripts/jquery-ui-1.12.1.custom/jquery-ui.css")" rel="stylesheet">
    }
}


@section ScriptPage {
    <script src="@Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script src="@Url.Content("~/scripts/jquery-ui-1.12.1.custom/jquery-ui.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.unobtrusive.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liProdutos').addClass("active");
            $("#datepicker").datepicker();
            $('.table').dataTable({
            "order": [[1, "asc"]]
        });
});
    </script>
}

Projeto01/Areas/Cadastros/Views/Produtos/Delete.cshtml
@model Modelo.Cadastros.Produto

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = " Deletar Produto";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Apagar Produto
    </div>
    <div class="panel-body">

       @Html.Partial("~/Areas/Cadastros/Views/Produtos/_PartialDetailsContentPanel.cshtml", Model)

    </div>

    <div class="panel-footer panel-info">
       <a href="#" class="btn btn-info" data-toggle="modal" data-target="#deleteConfirmationModal">Remover</a>
       @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-info" })
    </div>
</div>


<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" datadismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Confirmação de exclusão de PRODUTO</h4>
            </div>
            <div class="modal-body">
                <p>
                    Você está prestes a remover o produto @Model.Nome.ToUpper() do cadastro.
                </p>
                <p>
                    <strong>
                        Você está certo que deseja prosseguir?
                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "Produtos", FormMethod.Post, new { @id = "delete-form", role = "form" }))
                {
                    @Html.HiddenFor(m => m.ProdutoId)
                    @Html.AntiForgeryToken()
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="$('#delete-form').submit();">
                    Sim, exclua este produto.
                </button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Não, não exclua este produto.
                </button>
            </div>
        </div>
    </div>
</div>

@section ScriptPage {
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liProdutos').addClass("active");
        });
    </script>
}

Projeto01/Areas/Cadastros/Views/Produtos/Details.cshtml
@model Modelo.Cadastros.Produto

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = " Visualizar Produto";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Editar Produto
    </div>
    <div class="panel-body">
        @Html.Partial("~/Areas/Cadastros/Views/Produtos/_PartialDetailsContentPanel.cshtml", Model)



    </div>

    <div class="panel-footer panel-info">
        @Html.ActionLink("Alterar", "Edit", new { id = Model.ProdutoId }, new { @class = "btn btn-info" })
        @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-info" })
    </div>
</div>

@section styles{
    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet">
}

@section ScriptPage {
    <script src="@Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liProdutos').addClass("active");
            $('.table').dataTable({
                "order": [[1, "asc"]]
            });
        });
    </script>
    }

Projeto01/Areas/Cadastros/Views/Produtos/Edit.cshtml
@model Modelo.Cadastros.Produto

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Editar Produto";
}
@using (Html.BeginForm("Edit","Produtos",FormMethod.Post,new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">
              Editar Produto
        </div>
        <div class="panel-body">
            @*@Html.HiddenFor(model => model.Logotipo)
            @Html.HiddenFor(model => model.ProdutoId)*@
           @Html.Partial("~/Areas/Cadastros/Views/Produtos/_PartialEditContentPanel.cshtml")
        </div>
        <div class="panel-footer panel-info">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar alterações no Produto" class="btn btn-danger" />
                @Html.ActionLink("Retornar para a listagem de PRODUTOS", "Index", null, new { @class = "btn btn-warning" })
            </div>
            <br />
            <br />
        </div>
    </div>
    @section styles{
        <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet">
        <link href="@Url.Content("~/scripts/jquery-ui-1.12.1.custom/jquery-ui.css")" rel="stylesheet">
    }
}


@section ScriptPage {
    <script src="@Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script src="~/Scripts/datepicker-pt-BR.js"></script>
    <script src="~/scripts/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
    <script src="@Url.Content("~/scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.unobtrusive.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liProdutos').addClass("active");
            $("#datepicker").datepicker({
                dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
                dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
                dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
                monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
                monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
                dateFormat: 'dd/mm/yy',
                nextText: 'Próximo',
                prevText: 'Anterior'
            });
            $('.table').dataTable({
            "order": [[1, "asc"]]
        });
});
    </script>
}

Projeto01/Areas/Cadastros/Views/Produtos/Index.cshtml
@model IEnumerable<Modelo.Cadastros.Produto>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Listagem de PRODUTOS";
}

@if (@TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de PRODUTOS registrados
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ProdutoId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DataCadastro)
                    </th>
                    <th>Categoria</th>
                    <th>Fabricante</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProdutoId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DataCadastro)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Categoria.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fabricante.Nome)
                        </td>
                        <td>
                            @Html.ActionLink("Alterar", "Edit", new { id = item.ProdutoId }) |
                            @Html.ActionLink("Detalhes", "Details", new { id = item.ProdutoId }) |
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.ProdutoId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Registrar um novo PRODUTO", "Create", null, new { @class = "btn btn-success" })
    </div>
</div>


@section styles{
    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet">
}

@section ScriptPage {
    <script src="@Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script src="~/scripts/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
    <script src="@Url.Content("~/scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/scripts/jquery.unobtrusive.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liProdutos').addClass("active");
            $("#datepicker").datepicker({
                dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
                dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
                dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
                monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
                monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
                dateFormat: 'dd/mm/yy',
                nextText: 'Próximo',
                prevText: 'Anterior'
            });
            $('.table').dataTable({
                "order": [[1, "asc"]]
            });
        });
    </script>
}

Projeto01/Areas/Cadastros/Views/Produtos/_PartialDetailsContentPanel.cshtml
@model Modelo.Cadastros.Produto


<div class="form-group">
    @Html.LabelFor(model => model.Nome)<br />
    <div class="input-group">
        <span class="input-group-addon">
            <i class="glyphicon glyphicon-user"></i>
        </span>
        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
</div>
<div class="form-group">
    @Html.Label("Categoria")<br />
    <div class="input-group">
        <span class="input-group-addon">
            <i class="glyphicon glyphicon-user"></i>
        </span>
        @Html.EditorFor(model => model.Categoria.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
</div>
<div class="form-group">
    @Html.Label("Fabricante")<br />
    <div class="input-group">
        <span class="input-group-addon">
            <i class="glyphicon glyphicon-user"></i>
        </span>
        @Html.EditorFor(model => model.Fabricante.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
    </div>
</div>

Projeto01/Areas/Cadastros/Views/Produtos/_PartialEditContentPanel.cshtml
@model Modelo.Cadastros.Produto

<div class="form-horizontal">
  
    @Html.HiddenFor(model => model.ProdutoId)
   
    @if(ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Count() > 0))
    {   
        <div class="alert alert-danger alert-dismissible">
            @Html.ValidationSummary(false, "Verifique os seguintes erros:")
        </div>
    }
    
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DataCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control", id="datepicker" } })
            @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CategoriaId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.FabricanteId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("FabricanteId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FabricanteId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-offset-7 col-md-5">
        <div class="form-group">
            <input type="file" name="logotipo" id="logotipo" onchange='$("#upload-fileinfo").html($(this).val());'>
            <span id="upload-file-info"></span>
        </div>
        <div class="form-group">
            @Html.HiddenFor(model => model.Logotipo)
            @if(Model.Logotipo == null)
            {
                <div class="form-control-static"> Nenhuma imagem adicionada</div>
            }
            else
            {
                <div class="panel-body">
                    <img class="img-thumbnail" src="@Url.Action("GetLogotipo","Produtos",new {id = Model.ProdutoId})" style="display:block; margin-left:auto;margin-right:auto;" />
                </div>
                <div class="panel-footer">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="chkRemoverImagem" value="Sim" >Remover Imagem
                        </label>
                    </div>
                </div>
            }
        </div>
    </div>

</div>

Projeto01/Areas/Cadastros/Views/Produtos/_PorFabricante.cshtml
@model IEnumerable<Modelo.Cadastros.Produto>

<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de PRODUTOS registrados para o fabricante
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ProdutoId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>Categoria</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProdutoId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Categoria.Nome)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
    </div>
</div>